### ISSUE TITLE
生成arm64-v8a/libanyrtmp-jni.so时出错，环境在r10e和最新的都不可以。但是armeabi和v7a的都可以

### ISSUE THREAD

**Issue by etenel** [AnyRTC/anyRTC-RTMP-OpenSource#89]
WARNING:C:/Users/etenel/Desktop/anyRTC-RTMP-OpenSource-master/Prj-Android/jni/toolchain/../Android.mk:anyrtmp-jni: non-system libraries in linker flags: -lavformat -lavcodec -lavutil    
Android NDK:     This is likely to result in incorrect builds. Try using LOCAL_STATIC_LIBRARIES    
Android NDK:     or LOCAL_SHARED_LIBRARIES instead to list the library dependencies of the    
Android NDK:     current module    
D:/AndroidStudio/SDK/ndk-bundle/build//../toolchains/aarch64-linux-android-4.9/prebuilt/windows-x86_64/bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld.exe: cannot find -lavformat
D:/AndroidStudio/SDK/ndk-bundle/build//../toolchains/aarch64-linux-android-4.9/prebuilt/windows-x86_64/bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld.exe: cannot find -lavcodec
D:/AndroidStudio/SDK/ndk-bundle/build//../toolchains/aarch64-linux-android-4.9/prebuilt/windows-x86_64/bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld.exe: cannot find -lavutil
collect2.exe: error: ld returned 1 exit status
make: *** [C:/Users/etenel/Desktop/anyRTC-RTMP-OpenSource-master/Prj-Android/app/build/intermediates/ndkBuild/debug/obj/local/arm64-v8a/libanyrtmp-jni.so] Error 1
还有日志显示webrtc依赖有问题
Android NDK: Aborting (set APP_ALLOW_MISSING_DEPS=true to allow missing dependencies) . Stop.

**Comment by DyncEric** [comment]
应该是ffmpeg库不支持arm64的问题

**Comment by etenel** [comment]
好吧，感谢回复
