### ISSUE TITLE
怎么直接推送H2.64视频数据？

### ISSUE THREAD

**Issue by FanHongchuang** [AnyRTC/anyRTC-RTMP-OpenSource#91]
###  我的视频数据来自一台专业视频采集设备，可以提供H2.64视频流，请问使用这个库怎么直接推送H2.64视频流数据？

**Comment by DyncEric** [comment]
要自己进行适配，框架里面不支持直接推编码后的流，仅支持yuv原始数据

**Comment by FanHongchuang** [comment]
@DyncEric 支持的YUV原始数据是I420格式吗？

**Comment by DyncEric** [comment]
是的，I420可以。如果其他格式的也可以使用libyuv库进行转换

**Comment by FanHongchuang** [comment]
知道了，谢谢！

**Comment by FanHongchuang** [comment]
@DyncEric 请问接收YUV数据的接口在哪里？
